# Generated by Django 4.0.5 on 2023-07-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculomodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculomodel',
            options={'permissions': (('visualizar_catalogo', 'Puede visualizar el catálogo'), ('can_add_vehiculo_model', 'Puede agregar vehiculos al catálogo'))},
        ),
    ]
